---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
#- name: ubuntu-12.04
#  driver_config:
#    box: opscode-ubuntu-12.04
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
#- name: ubuntu-10.04
#  driver_config:
#    box: opscode-ubuntu-10.04
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
#- name: centos-5.9
#  driver_config:
#    box: opscode-centos-5.9
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list: 
    - "recipe[yum::epel]"
#    - "recipe[kandan::ruby]"
    - "recipe[kandan]"
  attributes:
#    rbenv:
#      rubies:
#        - 1.9.3-p392
#      global: 1.9.3-p392
#      gems:
#        1.9.3-p392:
#          - name: bundler
#            version: 1.3.5
